### ISSUE TITLE
How to get in touch with the team?

### ISSUE THREAD

**Issue by GiupiDeLuca** [AquaNet-ETH-Waterloo-2023/web#1]
Hey there, I find your project quite interesting and I'd love to help. How can I get in touch with anyone from the team?

**Comment by hexcowboy** [comment]
hi there,

we aren't currently hiring but we're leaving the hackathon project open source and i'll be happy to review any pull requests. if you want to submit a feature make sure to create an issue so we can discuss it first.

**Comment by GiupiDeLuca** [comment]
hey @hexcowboy thanks for your reply! I didn't mean as a hire, or code contributor. I meant to give you and the team a push (maybe grant, marketing, funds to develop further, etc..). I think this project might be a nice fit for the framework and ecosystem I work with. Let me know if you're interested and we could maybe have a quick chat.

**Comment by hexcowboy** [comment]
> hey @hexcowboy thanks for your reply! I didn't mean as a hire, or code contributor. I meant to give you and the team a push (maybe grant, marketing, funds to develop further, etc..). I think this project might be a nice fit for the framework and ecosystem I work with. Let me know if you're interested and we could maybe have a quick chat.

sure, i have some contact points on my website - cowboy.dev

**Comment by GiupiDeLuca** [comment]
@hexcowboy great, I just emailed you! talk soon
